# Generated by Django 5.0.14 on 2025-08-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='kind',
            field=models.CharField(choices=[('hero', 'Hero'), ('image', 'Image'), ('text', 'Text'), ('markdown', 'Markdown')], max_length=20),
        ),
    ]
